#!/bin/bash
# Script to help set up company logos with color options

echo "Setting up company logos with color options..."

# Create the company directory if it doesn't exist
mkdir -p /opt/odoo/route/abd-elhamed-saad-cv/images/company

echo "To set up your company logos, please follow these steps:"
echo ""
echo "1. Copy your company images to the company directory with these names:"
echo "   - msh-logo.png (for MSH for Tax Consultation)"
echo "   - breadfast-logo.png (for Breadfast)"
echo "   - freelance-logo.png (for Freelance Odoo Developer)"
echo "   - capstone-logo.png (for Capstone)"
echo "   - digitec-logo.png (for Digitec)"
echo "   - sbs-logo.png (for SBS)"
echo "   - knowledgebi-logo.png (for Knowledgebi)"
echo ""
echo "2. You can use commands like:"
echo "   cp /home/abdelhamed/Pictures/imge/2026-01-18_16-13.png /opt/odoo/route/abd-elhamed-saad-cv/images/company/sbs-logo.png"
echo ""
echo "3. Or copy and rename the image for each company:"
echo "   cp /path/to/your/image.png /opt/odoo/route/abd-elhamed-saad-cv/images/company/building-company.png"
echo ""
echo "4. If you want to create a default company logo, save it as:"
echo "   /opt/odoo/route/abd-elhamed-saad-cv/images/company/building-company.png"
echo ""
echo "5. Available color options for company borders (use in HTML):"
echo "   - random-color-1: Blue (#0078ff)"
echo "   - random-color-2: Green (#28a745)"
echo "   - random-color-3: Yellow (#ffc107)"
echo "   - random-color-4: Red (#dc3545)"
echo "   - random-color-5: Purple (#6f42c1)"
echo "   - random-color-6: Cyan (#17a2b8)"
echo "   - random-color-7: Orange (#fd7e14)"
echo "   - random-color-8: Teal (#20c997)"
echo "   - random-color-9: Pink (#e83e8c)"
echo "   - random-color-10: Gray (#6c757d)"
echo ""
echo "6. To add a new company, use the template in the HTML:"
echo "   <div class='job p-3 h-100 company-job random-color-X' style='background: #f8f9fa; border-radius: 0 4px 4px 0;'>"
echo "       <h4><img src='images/company/building-company.png' alt='Company Name Logo' class='company-logo' onerror='this.onerror=null; this.src='images/company/building-company.png';'> Job Title – Company Name</h4>"
echo "       <p>Start Year – End Year</p>"
echo "       <p>Description of your role and responsibilities at this company.</p>"
echo "   </div>"
echo ""
echo "After copying the images, your CV will automatically use them with the selected color!"