#!/bin/bash
# Script to set up company logos as circles with company names and multiple color options

echo "Setting up company logos as circles with company names and color options..."

# Create the company directory if it doesn't exist
mkdir -p /opt/odoo/route/abd-elhamed-saad-cv/images/company

echo "To set up your company logos with the circular style:"
echo ""
echo "1. First, copy your main image to use for all companies:"
echo "   cp /home/abdelhamed/Pictures/imge/2026-01-18_16-40.png /opt/odoo/route/abd-elhamed-saad-cv/images/company/main-logo.png"
echo ""
echo "2. Then create individual company logos by copying the main logo:"
echo "   cp /opt/odoo/route/abd-elhamed-saad-cv/images/company/main-logo.png /opt/odoo/route/abd-elhamed-saad-cv/images/company/msh-logo.png"
echo "   cp /opt/odoo/route/abd-elhamed-saad-cv/images/company/main-logo.png /opt/odoo/route/abd-elhamed-saad-cv/images/company/breadfast-logo.png"
echo "   cp /opt/odoo/route/abd-elhamed-saad-cv/images/company/main-logo.png /opt/odoo/route/abd-elhamed-saad-cv/images/company/freelance-logo.png"
echo "   cp /opt/odoo/route/abd-elhamed-saad-cv/images/company/main-logo.png /opt/odoo/route/abd-elhamed-saad-cv/images/company/capstone-logo.png"
echo "   cp /opt/odoo/route/abd-elhamed-saad-cv/images/company/main-logo.png /opt/odoo/route/abd-elhamed-saad-cv/images/company/digitec-logo.png"
echo "   cp /opt/odoo/route/abd-elhamed-saad-cv/images/company/main-logo.png /opt/odoo/route/abd-elhamed-saad-cv/images/company/sbs-logo.png"
echo "   cp /opt/odoo/route/abd-elhamed-saad-cv/images/company/main-logo.png /opt/odoo/route/abd-elhamed-saad-cv/images/company/knowledgebi-logo.png"
echo ""
echo "3. If you want to create a default company logo:"
echo "   cp /opt/odoo/route/abd-elhamed-saad-cv/images/company/main-logo.png /opt/odoo/route/abd-elhamed-saad-cv/images/company/building-company.png"
echo ""
echo "4. The images will appear as circles with shadows matching the border colors as specified in the CSS."
echo ""
echo "5. Available color options for company borders (use in HTML):"
echo "   - random-color-1: Blue (#0078ff)"
echo "   - random-color-2: Green (#28a745)"
echo "   - random-color-3: Yellow (#ffc107)"
echo "   - random-color-4: Red (#dc3545)"
echo "   - random-color-5: Purple (#6f42c1)"
echo "   - random-color-6: Cyan (#17a2b8)"
echo "   - random-color-7: Orange (#fd7e14)"
echo "   - random-color-8: Teal (#20c997)"
echo "   - random-color-9: Pink (#e83e8c)"
echo "   - random-color-10: Gray (#6c757d)"
echo ""
echo "6. To add a new company, use the template in the HTML:"
echo "   <div class='job p-3 h-100 company-job random-color-X' style='background: #f8f9fa; border-radius: 0 4px 4px 0;'>"
echo "       <h4><img src='images/company/building-company.png' alt='Company Name Logo' class='company-logo' onerror='this.onerror=null; this.src='images/company/building-company.png';'> Job Title – Company Name</h4>"
echo "       <p>Start Year – End Year</p>"
echo "       <p>Description of your role and responsibilities at this company.</p>"
echo "   </div>"
echo ""
echo "Note: The CSS already handles the circular shape and shadow effects."